name: Node.js CI/CD shopDEV

on:
  push:
    paths:
      - "shopdev-frontend/**"
      - "shopdev-backend/**"

jobs:
  build:
    runs-on: self-hosted
    if: contains(github.event.head_commit.message, 'deploy')
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
        #   cache: "npm"

      - name: Install dependencies backend
        run: cd shopdev-backend && npm install
      - name: Run stop backend
        run: |
          if pm2 jlist | grep -q '"name":"shopdev-backend"'; then
            pm2 delete shopdev-backend
          fi
      - name: Run start backend
        run: cd shopdev-backend && npm run pm2

      - name: Install dependencies frontend
        run: cd shopdev-frontend && npm install

      - name: Build frontend
        run: cd shopdev-frontend && npm run build
